### ISSUE TITLE
Restart of container causing error

### ISSUE THREAD

**Issue by bunkerman** [leepeuker/movary#204]
Hi again :)

When I restart the container I get "error: failed switching to "root": operation not permitted" and can't access movary.
If I recreate the container it works again. I'm using Portainer for container management.
If I set the user root it also works when restarting the container.

![grafik](https://user-images.githubusercontent.com/7395381/210139481-0c5287d1-0937-4190-8004-318d6fb8157d.png)

The standard application user should be the docker user.

**Comment by leepeuker** [comment]
@bunkerman I had the situation now that I had to always recreate the container. I could solve it by setting the user/group id of the container via `--user 1000:1000`, that fixed the `"error: failed switching to "root": operation not permitted"` issue for me

**Comment by bunkerman** [comment]
thx4info! is this within the the docker run command? I tried it with portainer, but it didn't work

**Comment by leepeuker** [comment]
It is `--user 1000:1000` with the docker run command or `user: "1000:1000"` with docker compose. You may need to use different UID/GID instead of 1000, try to match the ids with the ones of the owner of the mounted storage directory.

Or maybe your error is caused by something completely different :see_no_evil:

**Comment by bunkerman** [comment]
yeah exactly. I have OMV and portainer, so it's 1000:100
the command in portainer is '--user' '1000:100'
but I have the same error
