### ISSUE TITLE
Slow loading via Docker

### ISSUE THREAD

**Issue by JVT038** [leepeuker/movary#218]
I just set up a development environment, and I've noticed that the website takes a couple of seconds to load.
While 'a couple of seconds' doesn't sound that much, it does _feel_ like a long time, compared to how fast websites usually are.
Perhaps it's just my computer (I doubt that) or my Wi-Fi (I doubt that too).

Rather, I think the code is slow and PHP is a relatively slow programming language. Other languages like Go are faster. But still, I've developed plenty of PHP applications and they've never been this slow.

I haven't really looked into the codebase yet, I just looked around the website, but I already have one recommendation. Reduce the amount of different pages. If you use fewer pages, things will generally be faster to use.
For example: 
* Use [bootstrap tabs](https://getbootstrap.com/docs/5.2/components/navs-tabs/#javascript-behavior) in the settings to navigate, instead of having a different page for each setting.
* Use [modals](https://getbootstrap.com/docs/5.2/components/modal/) for logging a movie and other smaller tasks that can be done at the homepage.

If you follow this advice, the pages have to load less and the modals will only be loaded once (at the page initialization). The additional HTML / JS code won't make that much of a different (performance wise). I've written applications with 5 different modals on the same page, and it worked fine. (but the codebase was a mess, so I recommend spreading the modals across multiple files and then include those files in the homepage)

Lastly, if the frontend assets (such as CSS and JS) get very big (and they already are, considering JQuery and Bootstrap are included), you could use something like [Vite](https://vitejs.dev/) to compress those assets and minimize the initial asset load.

**Comment by leepeuker** [comment]
Hm, I think there maybe is issue on your host, the website should not be that slow. The demo applications [dashboard page](https://demo.movary.org/testUser/dashboard) (which has one of the longest loading times of all pages) has a load time until finish of ~700ms in firefox without browser cache and ~300ms with cache for me. This is hosted on a pretty small VPS with 1vCPU and 1GB RAM.

I did not invest much time thinking about page performance yet because I had no issues with it myself and nothing was reported until now. You are very welcome to suggest improvements and contribute PRs if you want to.

**Comment by JVT038** [comment]
I suspect it has something to do with the Docker engine, because without Docker it loads faster.

**Comment by leepeuker** [comment]
Closing ticket, does not seem to be an issue with the image and even if it is, https://github.com/leepeuker/movary/issues/206 should hopefully fix it
