### ISSUE TITLE
Setup matrix server for better communication

### ISSUE THREAD

**Issue by leepeuker** [leepeuker/movary#293]
Currently the main communication platform are Github issues. There is a subreddit I have created, but this does not really match the FOSS philosophy of this project (still probably a good way to interact with casual users).

 I will setup a matrix server for more direct/instant communication between contributors/users/supporters.

It will probably use the domain `matrix.movary.org` if there are no better ideas.

**Comment by JVT038** [comment]
Honestly? I don't have any experience either lol.

It's just that I've always wanted to try Matrix, because it's an actual decentralized and FOSS alternative to non-FOSS platforms like Discord.
So I can't really give you any feedback, but I would like to just try Matrix one time, and I thought this would be a good opportunity to do so.

**Comment by leepeuker** [comment]
Update: I was able to activate registrations, but I still have an issue with sending emails via synpase. They do not contain the correct server url. I have asked for help on [reddit](https://www.reddit.com/r/matrixdotorg/comments/126g4yu/synapse_emails_are_using_wrong_server_url)

**Comment by leepeuker** [comment]
Okay, now to end this whole thing...

Matrix room: https://matrix.to/#/#movary:leepeuker.dev

You need a [client](https://matrix.org/clients/) and an account (for registering a new one you need [homeserver](https://joinmatrix.org/servers/)) to join.

I am hosting a homeserver and a [client](https://element.leepeuker.dev/) myself. We will see how this works out ;)
