### ISSUE TITLE
Show current streaming providers for movie

### ISSUE THREAD

**Issue by JVT038** [leepeuker/movary#331]
When I visit a movie, I want to know where I can legally watch the movie online.
Example on TMDB:

![image](https://user-images.githubusercontent.com/47184046/236635451-99c87cc0-c0db-4abc-b4ae-e5d32d146e4c.png)

I don't know if it's possible to fetch these details via the TMDB API, but if it is, then we should do that.

**Comment by leepeuker** [comment]
There is a TMDB API endpoint for this: https://developer.themoviedb.org/reference/movie-watch-providers: `https://api.themoviedb.org/3/movie/{movie_id}/watch/providers`

It provides movie streaming information per country. We need to add an option for users to set the preferred country (in the general user settings I guess?), so that we can provide the streaming information matching the users location.
