### ISSUE TITLE
Movies are not sorted correctly  if watched on same day

### ISSUE THREAD

**Issue by muhammad-ans** [leepeuker/movary#472]
### Description

If we mark as watched two movies on the same day 
Let's say i watched  sicario first and then john wick.
In last plays sicario would be shown as latest watched.
 

### Version

0.57.0

### Steps to Reproduce

Just add two movies on the same day 
e.g.
sicario first and then john wick.
In last plays sicario would be shown as latest watched.

### Client Platform

None

**Comment by pbogre** [comment]
i noticed this bug as well. it might have something to do with the date/time format that is used for the watch date column in the database

**Comment by muhammad-ans** [comment]
I think the watch date column just stores date 
if two movies have same date it sorts them alphabetically

**Comment by pbogre** [comment]
you're probably right. to fix this issue (and honestly a general improvement) we could use unix millis to store watch dates and then convert it as needed for UI. 

Or simply had the time of day at which it was watched.

However i'm just not 100% on how date times are stored so i'm not sure

**Comment by leepeuker** [comment]
Thanks for reporting this issue @muhammad-ans 

The watch date is a simple date, it does not contain time. Currently the last plays are ordered only by this date. If you have watched two different movies on the same day your database decides how they are ordered right now (e.g. ordering by last inserted) because it is not explicitly defined in Movary.

I do not like the idea of adding a time to the watch date because it makes things more difficult to manage for the user and for the development (e.g. timezones differences and stuff). Having to manage only the date is much simpler and I think enough in most cases, it does not happen that often that users watch multiple movies in one day I believe.

But we should definitely find a solution for cases where this does happen.

I am currently thinking about adding a new attribute "position" (or something like that) to movie watch dates, this way you could for example set the "position" for the first watched movie to 1 and the for the second movie to 2. "position" will than be used as secondary order parameter. Newly added watch dates always get the "position" 1 as default, except if there is already one or more watched movies for the date, than we just start adding +1 to the "position" for every new movie added to the date. In case you have added the plays in the wrong order you can manually correct the "position" numbers 🤔

**Comment by muhammad-ans** [comment]
Sounds good

**Comment by leepeuker** [comment]
I have added a new attribute `position` to watch dates and updated the "Edit Watch Date" modal to be a bit more user friendly.

Before: 
![image](https://github.com/leepeuker/movary/assets/19872901/241b953c-58c9-4288-a816-e098627aaec9)

Now:
![image](https://github.com/leepeuker/movary/assets/19872901/c4d25fc0-0e7d-4e15-8f62-e5b1b0501c08)

![image](https://github.com/leepeuker/movary/assets/19872901/43ed046c-03b9-463f-8ba0-504669633d10)

Open todos:
- automatically set the correct position if a play is added to a date which already has plays (currently plays is always 1 when adding a watch date on default)
- automatically set the correct positions on history imports
- test everything again

**Comment by leepeuker** [comment]
This part of the nightly tag now, @muhammad-ans @sahinakkaya you are welcome to use it. If you run into any problems please contact me, more testers are always appreciated :D

**Comment by leepeuker** [comment]
You probably have to run the database migrations?

**Comment by sahinakkaya** [comment]
Oh, yeah I forgot to run it sorry. After running migrations the error went away but now clicking on "Advenced mode" doesn't do anything. And in the console following error is thrown "Uncaught ReferenceError: toggleWatchDateAdvancedMode is not defined"

**Comment by sahinakkaya** [comment]
OK, you are right again 🤦‍♂️ Sorry for wasting your precious time twice. I tested the new feature and it works as expected too. Thank you!

**Comment by leepeuker** [comment]
Ah no problems, at least the migrations should be done automatically anyway, so I feel responsible for this problem anyway :D

**Comment by muhammad-ans** [comment]
Thanks for this feature. Working as expected but there is no position attribute in export of history. With current implementation it reverses the positions when imported.
